### PR TITLE
Add logout button and restore error page content

### PR DESCRIPTION
**Pull request by redfern314**
Per comments in #4, splitting this commit out into a separate PR for clarity. This makes 2 changes:
1. Adds a Log Out button to the logged-in screens (not visible when not authenticated or authenticated with an unauthorized account). This makes testing user auth easier, and is also just a good thing to have.
Screenshot 2024-04-22_22-15-25

2. Reverts an old change that unexpectedly hid error messages in order to save some vertical space on the home page. @clizzin, as you requested in the other PR, I restored the vertical gap on the main page to diverge less from upstream; let me know if you think the gap is too much and I can remove it again 😂.

----
Screenshot 2024-04-22_22-57-19
----
Screenshot 2024-04-22_22-19-37
----
Screenshot 2024-04-22_22-20-53
----
Screenshot 2024-04-22_22-59-35
----

### CODE REVIEW

**Review by clizzin — APPROVED** [review]
Haha it's true, I don't like the gap, but I'll deal. LGTM!

**Comment by eplusminus** [comment]
I don't want to nitpick unnecessarily, but just to help me better understand what's going on... I am still confused about what the connection is between the changes related to `.tagline` and the addition of the logout link.

In the other PR, in the thread about whether some stuff might be out of scope, 3 changes were mentioned:
1. Adding the logout link in `userTools.ejs`
2. Removing a `<div class="tagline">` element, in `index.ejs`
3. Removing a CSS rule that made the `tagline` div invisible, in `_custom.scss`

I understand the purpose of 1 - that wasn't what I was talking about and it's clearly relevant to the auth issue.

2 seemed like it was meant to accomplish the same thing as 3 without the CSS rule. But it looks to me like you did _not_ carry that change over into this PR, and it's been reverted in the original PR, so now the `tagline` element will appear? In other words, this PR doesn't seem to quite match what you originally did. Was that intentional? Is there some mechanism I'm not seeing where the message about logging out is actually inside `tagline`?

I'm still missing how the `tagline` CSS class is relevant to the new element in `userTools.ejs`, which doesn't seem to be enclosed in anything with that class (looking at `index.ejs`, I see `userTools.ejs` being included within `header.masthead > div.container`).

**Comment by clizzin** [comment]
I can answer this—if you search the code for other uses of the `tagline` class, you'll find it used in the layouts for [403](https://github.com/sfneofuturists/chive/blob/788ea2ffc6d26b3e9600c318f70b36bf7b6ea279/layouts/errors/403.ejs#L8) and [404](https://github.com/sfneofuturists/chive/blob/788ea2ffc6d26b3e9600c318f70b36bf7b6ea279/layouts/errors/404.ejs#L8) error pages. The CSS rule `.tagline { display: none; }` caused those error messages to be hidden, but we want to show them, hence we remove that rule.

The reason Derek didn't retain the 2nd change (removing the `.tagline` element in `index.ejs`) is because I [told him](https://github.com/sfneofuturists/chive/pull/4#discussion_r1573194062) to restore that element, to reduce divergence from upstream, and that I would just live with the fact that it creates some extra vertical space on the page.

**Comment by redfern314** [comment]
Exactly - thanks Topher!

**Pull request merged**
